# -*- coding: utf-8 -*-
{
    'name': 'ACMST Admissions',
    'summary': 'Admissions portal with lookup, OTP auth, profile, and PDF form',
    'version': '17.0.1.0.0',
    'category': 'Website',
    'author': 'ACMST',
    'website': 'https://example.com',
    'license': 'LGPL-3',
    'depends': ['base', 'web', 'website', 'portal', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/admissions_data.xml',
        'data/cron.xml',
        'data/server_actions.xml',
        'views/menu.xml',
        'views/program_views.xml',
        'views/year_views.xml',
        'views/candidate_views.xml',
        'views/settings_views.xml',
        'views/import_wizard_views.xml',
        'views/import_job_views.xml',
        'views/otp_log_views.xml',
        'views/res_config_settings_views.xml',
        'views/website_templates.xml',
        'views/assets.xml',
        'reports/report_actions.xml',
        'reports/report_templates.xml',
    ],
    'installable': True,
    'application': True,
}
